#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input critical "envoy-component/fqdn" || true
db_input critical "envoy-component/username" || true
db_input critical "envoy-component/password" || true
db_go
